### ISSUE TITLE
T2_Realidad Aumentada animación 

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-team-vo#1]
[RA_T2_Animacion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-team-vo/files/14950303/RA_T2_Animacion.pdf)

**Comment by MLR062998** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
